import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { router } from "expo-router";
import { onAuthStateChanged } from "firebase/auth";
import {
  collection,
  doc,
  getDoc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import React, { useEffect, useState } from "react";
import {
  ActivityIndicator,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { auth } from "../firebase/auth";
import { db } from "../firebase/firestore";

const NAVY = "#14213D";
const GREEN = "#2E9E5B";
const GRAY = "#6B7280";

type ScheduleItem = {
  id: string;
  title: string;
  time: string;
  icon?: string;
  color?: string;
};

const quickActions = [
  { label: "Raise Complaint", icon: "document-text-outline", color: "#5B4FCF" },
  { label: "My Complaints", icon: "document-outline", color: "#2E6FD9" },
  { label: "Visitor Approval", icon: "person-add-outline", color: "#2E9E5B" },
  { label: "Maintenance (Pay)", icon: "leaf-outline", color: "#2E9E5B" },
  { label: "Notices", icon: "clipboard-outline", color: "#E07A1F" },
  { label: "Emergency Contacts", icon: "medkit-outline", color: "#D93B3B" },
];

const navItems = [
  { label: "Home", icon: "home", iconOutline: "home-outline", active: true, route: "/" },
  { label: "Community", icon: "people", iconOutline: "people-outline", active: false, route: "/community" },
  { label: "Notices", icon: "calendar-outline", iconOutline: "calendar-outline", active: false, route: "/notices" },
  { label: "Profile", icon: "person-outline", iconOutline: "person-outline", active: false, route: "/profile" },
];

export default function HomeDashboard() {
  const [member, setMember] = useState<any>(null);
  const [schedules, setSchedules] = useState<ScheduleItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const unsubscribeAuth = onAuthStateChanged(auth, (user) => {
      if (!user) {
        router.replace("/login");
        return;
      }
      fetchMemberData(user.uid);
    });

    // Real-time Firestore subscription for "Today's Schedule" generated by Admin
    const scheduleQuery = query(
      collection(db, "schedules"),
      orderBy("createdAt", "asc")
    );

    const unsubscribeSchedules = onSnapshot(
      scheduleQuery,
      (snapshot) => {
        const fetchedSchedules: ScheduleItem[] = snapshot.docs.map((docSnap) => ({
          id: docSnap.id,
          title: docSnap.data().title,
          time: docSnap.data().time,
          icon: docSnap.data().icon || "calendar-outline",
          color: docSnap.data().color || NAVY,
        }));
        setSchedules(fetchedSchedules);
      },
      (error) => {
        console.log("Error listening to schedules:", error);
      }
    );

    return () => {
      unsubscribeAuth();
      unsubscribeSchedules();
    };
  }, []);

  const fetchMemberData = async (uid: string) => {
    try {
      const docRef = doc(db, "members", uid);
      const docSnap = await getDoc(docRef);
      if (docSnap.exists()) {
        setMember(docSnap.data());
      }
    } catch (error) {
      console.log("Dashboard fetch error:", error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color={NAVY} />
      </View>
    );
  }

  const initials = member && member.name ? member.name.trim()[0].toUpperCase() : "U";

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <View style={styles.page}>
          {/* Header */}
          <View style={styles.header}>
            <View style={styles.headerCenter}>
              <View style={styles.avatarCircle}>
                <Text style={styles.avatarText}>{initials}</Text>
              </View>
              <View style={{ marginLeft: 10 }}>
                <Text style={styles.hello}>Hello, {member && member.name ? member.name : "there"}</Text>
                <Text style={styles.flat}>
                  {member && member.flatNumber ? member.flatNumber + ", " + member.societyName : "Complete your profile"}
                </Text>
              </View>
            </View>
          </View>

          {/* Maintenance Card */}
          <LinearGradient colors={[NAVY, GREEN]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.dueCard}>
            <View style={styles.dueIconCircle}>
              <Ionicons name="shield-checkmark-outline" size={24} color="#fff" />
            </View>
            <View style={{ flex: 1, marginLeft: 14 }}>
              <Text style={styles.dueLabel}>Maintenance Due</Text>
              <Text style={styles.dueAmount}>₹{member && member.maintenanceDue ? member.maintenanceDue : 0}</Text>
              <Text style={styles.dueDate}>Due {member && member.dueDate ? member.dueDate : "N/A"}</Text>
            </View>
            <TouchableOpacity style={styles.payButton} onPress={() => router.push("/maintenance" as any)}>
              <Text style={styles.payButtonText}>Pay Now</Text>
            </TouchableOpacity>
          </LinearGradient>

          {/* Quick Actions */}
          <View style={styles.sectionHeaderRow}>
            <Text style={styles.sectionTitle}>Quick Actions</Text>
          </View>

          <View style={styles.grid}>
            {quickActions.map((action) => (
              <TouchableOpacity
                key={action.label}
                style={styles.gridItem}
                activeOpacity={0.8}
                onPress={() => handleQuickActionPress(action.label)}
              >
                <View style={[styles.gridIconCircle, { backgroundColor: action.color + "1A" }]}>
                  <Ionicons name={action.icon as any} size={22} color={action.color} />
                </View>
                <Text style={styles.gridLabel}>{action.label}</Text>
              </TouchableOpacity>
            ))}
          </View>

          {/* Today's Schedule Section */}
          <View style={styles.sectionHeaderRow}>
            <Text style={styles.sectionTitle}>🗓 Today's Schedule</Text>
          </View>

          <View style={styles.upcomingList}>
            {schedules.length === 0 ? (
              <View style={styles.emptyContainer}>
                <Ionicons name="calendar-outline" size={32} color={GRAY} />
                <Text style={styles.emptyText}>No events scheduled for today.</Text>
              </View>
            ) : (
              schedules.map((item, index) => (
                <View
                  key={item.id}
                  style={[styles.upcomingRow, index !== schedules.length - 1 && styles.upcomingRowDivider]}
                >
                  <View style={[styles.gridIconCircle, { backgroundColor: (item.color || NAVY) + "1A" }]}>
                    <Ionicons name={(item.icon || "time-outline") as any} size={20} color={item.color || NAVY} />
                  </View>
                  <View style={{ flex: 1, marginLeft: 12 }}>
                    <Text style={styles.upcomingTitle}>{item.title}</Text>
                  </View>
                  <View style={styles.dateChip}>
                    <Ionicons name="time-outline" size={13} color={GRAY} />
                    <Text style={styles.dateChipText}>{item.time}</Text>
                  </View>
                </View>
              ))
            )}
          </View>
        </View>
      </ScrollView>

      {/* Navigation */}
      <View style={styles.bottomNavWrap}>
        <View style={styles.bottomNav}>
          {navItems.map((item) => (
            <TouchableOpacity
              key={item.label}
              style={[styles.navItem, item.active && styles.navItemActive]}
              onPress={() => router.push(item.route as any)}
            >
              <Ionicons name={(item.active ? item.icon : item.iconOutline) as any} size={20} color={item.active ? NAVY : GRAY} />
              <Text style={[styles.navLabel, item.active && styles.navLabelActive]}>{item.label}</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>
    </SafeAreaView>
  );

  function handleQuickActionPress(label: string) {
    switch (label) {
      case "Raise Complaint": router.push("/raisecomplaint" as any); break;
      case "My Complaints": router.push("/my-complaints" as any); break;
      case "Notices": router.push("/notices" as any); break;
      case "Emergency Contacts": router.push("/emergency-contacts" as any); break;
      case "Maintenance (Pay)": router.push("/maintenance" as any); break;
      case "Visitor Approval": router.push("/visitor-approval" as any); break;
      default: break;
    }
  }
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F7F8FA" },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  scrollContent: { flexGrow: 1, paddingBottom: 10 },
  page: { flex: 1, width: "100%", paddingHorizontal: 20 },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 20, paddingBottom: 16 },
  headerCenter: { flexDirection: "row", alignItems: "center", flex: 1 },
  avatarCircle: { width: 42, height: 42, borderRadius: 21, backgroundColor: NAVY, justifyContent: "center", alignItems: "center" },
  avatarText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  hello: { fontSize: 16, fontWeight: "700", color: NAVY },
  flat: { fontSize: 12, color: GRAY, marginTop: 2 },
  dueCard: { flexDirection: "row", alignItems: "center", borderRadius: 18, padding: 20, elevation: 6 },
  dueIconCircle: { width: 46, height: 46, borderRadius: 23, backgroundColor: "rgba(255,255,255,0.18)", justifyContent: "center", alignItems: "center" },
  dueLabel: { fontSize: 12, color: "rgba(255,255,255,0.8)" },
  dueAmount: { fontWeight: "800", color: "#fff", marginTop: 2, fontSize: 26 },
  dueDate: { fontSize: 12, color: "rgba(255,255,255,0.8)", marginTop: 2 },
  payButton: { backgroundColor: "#fff", paddingHorizontal: 16, paddingVertical: 10, borderRadius: 10 },
  payButtonText: { color: NAVY, fontWeight: "700", fontSize: 13 },
  sectionHeaderRow: { marginTop: 28, marginBottom: 14 },
  sectionTitle: { fontWeight: "700", color: "#111827", fontSize: 16 },
  grid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-start", gap: 10 },
  gridItem: { backgroundColor: "#fff", borderRadius: 16, paddingVertical: 18, paddingHorizontal: 14, alignItems: "flex-start", width: "30%", elevation: 1 },
  gridIconCircle: { width: 38, height: 38, borderRadius: 12, justifyContent: "center", alignItems: "center", marginBottom: 10 },
  gridLabel: { fontSize: 13, fontWeight: "600", color: "#111827", lineHeight: 17 },
  upcomingList: { backgroundColor: "#fff", borderRadius: 14, elevation: 1 },
  upcomingRow: { flexDirection: "row", alignItems: "center", paddingVertical: 14, paddingHorizontal: 16 },
  upcomingRowDivider: { borderBottomWidth: 1, borderBottomColor: "#F0F1F3" },
  upcomingTitle: { fontSize: 14, fontWeight: "700", color: "#111827" },
  dateChip: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "#F1F2F4", borderRadius: 8, paddingVertical: 6, paddingHorizontal: 10 },
  dateChipText: { fontSize: 12, color: GRAY, fontWeight: "600" },
  emptyContainer: { padding: 24, alignItems: "center", justifyContent: "center" },
  emptyText: { color: GRAY, fontSize: 13, marginTop: 8 },
  bottomNavWrap: { borderTopWidth: 1, borderTopColor: "#E5E7EB", backgroundColor: "#fff", alignItems: "center" },
  bottomNav: { width: "100%", flexDirection: "row", justifyContent: "space-around", paddingVertical: 10, paddingHorizontal: 20 },
  navItem: { alignItems: "center", gap: 3, paddingHorizontal: 14, paddingVertical: 4, borderRadius: 10 },
  navItemActive: { backgroundColor: "#EEF2FF" },
  navLabel: { fontSize: 11, color: GRAY },
  navLabelActive: { color: NAVY, fontWeight: "700" },
});